services:
  site:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: astro-prod
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0
      - PORT=4321
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
